### ISSUE TITLE
*BUG* File: [vector_ops.c] Line: [18]

### ISSUE THREAD

**Issue by MMasterson** [ArchangelSDY/PyPuzzle#10]
While trying to compare two vectors I get the following error

on Ubuntu 14.04

```shell
*BUG* File: [vector_ops.c] Line: [18]
Aborted (core dumped)
```
I am comparing to a value in mongoDB and I have verified both vec and doc['vector'] are not null.

My program breaks here
```pyhton
                                distance = puzzle.get_distance_from_cvec(vec,doc['vector'])
```
I am comparing to a value in mongoDB and I have verified both vec and doc['vector'] are not null.

**Comment by MMasterson** [comment]
I have tried a different method, and I receive a different error.

I know store a uncompressed version of the vector in the database as "vector", and when I pull it out and print it, its fine. But i try to uncompress it I get 

````shell
Segmentation fault (core dumped)
````
on the line
````python
uncompressedFromDB = puzzle.uncompress_cvec(vec2)
````

where

````python
vec2 = doc['vector']
````

**Comment by MMasterson** [comment]
third approach leaves me with the original error 

```shell
*BUG* File: [vector_ops.c] Line: [18]
Aborted (core dumped)
```
on line

```pyhton
                                distance = puzzle.get_distance_from_cvec(vec,doc['vector'])
```

more code for reference 
````python
  docs = db.releases.find({"words":word})
                        for doc in docs:
                                print doc['vector']
                                vec2 = doc['vector']
                                print "about to perform distance"
                                distance = puzzle.get_distance_from_cvec(vec,vec2)
````

**Comment by ArchangelSDY** [comment]
Looks like a malformed vec. Can you check the type of your `vec` and `vec2` using `print type(vec), type(vec2)`?

**Comment by MMasterson** [comment]
@ArchangelSDY 
Seems I have 
````shell
<type 'tuple'>
````

**Comment by ArchangelSDY** [comment]
Are their lengths same?

**Comment by MMasterson** [comment]
I stand corrected 
one was 
````python
<type 'tuple'>
`````
the other
````python
<type 'list'>
`````

simple fix by adding 
````python
vec2 = tuple(doc['vector']
`````
