### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by chuckytah** [ArchangelSDY/PyPuzzle#11]
src/pypuzzle.c:2:10: fatal error: 'puzzle.h' file not found
    #include <puzzle.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1

what should i do?

**Comment by ArchangelSDY** [comment]
You should have libpuzzle installed first.

**Comment by chuckytah** [comment]
=x my bad, solved, sorry!
