### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by M0rtenB** [ArchangelSDY/PyPuzzle#8]
I get this error, either with pip og setup.py. Using brewed Python 2.7.9 or 3.4.2 on OS X 10.10.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d0d679c363c1> in <module>()
----> 1 import pypuzzle

ImportError: dlopen(/usr/local/lib/python3.4/site-packages/pypuzzle.so, 2): Symbol not found: _PyInt_AsLong
  Referenced from: /usr/local/lib/python3.4/site-packages/pypuzzle.so
  Expected in: flat namespace
 in /usr/local/lib/python3.4/site-packages/pypuzzle.so

**Comment by ArchangelSDY** [comment]
It looks like this error is generated in a Python 3.4 environment. Since PyPuzzle hasn't been ported to Python 3.x yet, you may have to force a Python 2 environment using tools like virtualenv (`virtualenv -p python2`).
