### ISSUE TITLE
missing setup.py

### ISSUE THREAD

**Issue by Jskarie** [ArchangelSDY/PyPuzzle#9]
when I do a pip install pypuzzle I get
IOError: [Errno 2] No such file or directory: '[omitted]/virenv/deysite/build/pypuzzle/setup.py'

Fix: 
pip install pypuzzle==1.2

**Comment by ArchangelSDY** [comment]
Seems strange. 1.2 is the default version at PyPI so `pip install pypuzzle` actually works the same as `pip install pypuzzle==1.2`. Besides I can't reproduce the error on my latest Arch Linux.

**Comment by Jskarie** [comment]
I'm going to close this down.  If someone else experiences this problem, they have a very easy work-around and you can re-open it.
